name: A11yWatch - The Accessibility Suite
on: [pull_request, push]
author: A11yWatch
branding:
  icon: "shield"
  color: "gray-dark"
description: Setup A11yWatch CLI in your GitHub Actions workflow.
inputs:
  WEBSITE_URL:
    description: Website domain to scan
    required: true
  EXTERNAL:
    description: Use the A11yWatch external api hosted by us [Fast Testing]
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Install Rust
      shell: bash
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Install the A11yWatch CLI
      shell: bash
      run: cargo install a11ywatch_cli
    - name: Start A11yWatch Service
      if: ${{ !env.EXTERNAL }}
      shell: bash
      run: a11ywatch start
    - name: Wait for Healthy Container
      if: ${{ !env.EXTERNAL }}
      shell: bash
      run: |
        attempt=0

        while [ $attempt -le 10 ]; do
            attempt=$(( $attempt + 1 ))
            echo "Waiting for server to be up (attempt: $attempt)..."
            result=$(docker logs api)
            if grep -q 'Server ready' <<< $result ; then
              echo "A11yWatch ready!"
              break
            fi
            sleep 0.3
        done
    - name: Scan Website
      shell: bash
      run: |
        if [ ${{ inputs.EXTERNAL }} ]; then
          a11ywatch scan --url "${{ inputs.WEBSITE_URL }}" --external
        else
          a11ywatch scan --url "${{ inputs.WEBSITE_URL }}"
        fi
    - name: Stop A11yWatch Service
      if: ${{ !env.EXTERNAL }}
      shell: bash
      run: a11ywatch stop
