name: A11yWatch - The Accessibility Suite
on: [pull_request, push]
author: A11yWatch
branding:
  icon: "shield"
  color: "gray-dark"
description: Setup A11yWatch CLI in your GitHub Actions workflow.
inputs:
  WEBSITE_URL:
    description: Website domain to scan
    required: true
  EXTERNAL:
    description: Use the A11yWatch external api hosted.
    required: false
    default: ""
outputs:
  results:
    description: "Website Results"
    value: ${{ steps.a11ywatch-results-generator.outputs.results }}
runs:
  using: composite
  steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y

    - name: Install the A11yWatch CLI
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: cargo install a11ywatch_cli

    - name: Start A11yWatch Service
      if: ${{ !inputs.EXTERNAL }}
      shell: bash
      run: a11ywatch start

    - name: Wait for Healthy Container
      if: ${{ !inputs.EXTERNAL }}
      shell: bash
      run: |
        attempt=0

        while [ $attempt -le 10 ]; do
            attempt=$(( $attempt + 1 ))
            echo "Waiting for server to be up (attempt: $attempt)..."
            result=$(docker logs api)
            if grep -q 'Server ready' <<< $result ; then
              echo "A11yWatch ready!"
              break
            fi
            sleep 0.3
        done

    - name: A11ywatch Scan
      id: a11ywatch-results-generator
      shell: bash
      run: |

        if ${{ inputs.EXTERNAL }} = "true"; then
          a11ywatch scan --url "${{ inputs.WEBSITE_URL }}" --external > ./results.json
        else
          a11ywatch scan --url "${{ inputs.WEBSITE_URL }}" > ./results.json
        fi

        JSON="$(cat ./results.json)"

        echo "::set-output name=results::$(echo ${JSON//'%'/'%25'})"

    - name: Stop A11yWatch Service
      if: ${{ !inputs.EXTERNAL }}
      shell: bash
      run: a11ywatch stop
