name: A11yWatchBot
on: [pull_request]
jobs:
  run-container:
    name: End to End
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: A11yWatch website scan
        uses: ./
        with:
          WEBSITE_URL: https://a11ywatch.com
          FAIL_TOTAL_COUNT: 3400
          EXTERNAL: false
          SITE_WIDE: true
          SUBDOMAINS: false
          TLD: false
          LIST: true
          UPGRADE: false
          # A11YWATCH_TOKEN: ${{ secrets.A11YWATCH_TOKEN }}
