name: Tests
on: [pull_request]
jobs:
  run-container:
    name: End to End
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: A11yWatch website scan
        uses: ./
        with:
          WEBSITE_URL: https://a11ywatch.com
          FAIL_TOTAL_COUNT: 40
          EXTERNAL: false
          SITE_WIDE: true
          SITEMAP: true
          SUBDOMAINS: false
          TLD: false
          LIST: true
          UPGRADE: true
          UPLOAD: true
        env:
          DEFAULT_RUNNERS: htmlcs