name: A11yWatchBot
on: [pull_request]
jobs:
  run-container:
    name: End to End
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: A11yWatch website scan
        uses: ./
        with:
          WEBSITE_URL: https://www.jeffmendez.com
          FAIL_ERROR_COUNT: 1400
          EXTERNAL: false
          SITE_WIDE: true
          # A11YWATCH_TOKEN: ${{ secrets.A11YWATCH_TOKEN }}
