name: Tests
on: [pull_request]
jobs:
  run-container:
    name: End to End
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: A11yWatch website scan
        uses: ./
        with:
          WEBSITE_URL: https://www.ck12.org/search/?q=hello&referrer=search
          FAIL_TOTAL_COUNT: 10
          EXTERNAL: false
          SITE_WIDE: true
          SITEMAP: true
          SUBDOMAINS: true
          TLD: true
          LIST: true
          UPGRADE: true
