name: A11yWatchBot
on: [pull_request, push]
jobs:
  run-container:
    name: End to End
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        if: ${{ env.DOCKER_LAYER_CACHE }}
      - name: Install Rust
        if: steps.cache.outputs.cache-hit != 'true'
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Install the A11yWatch CLI
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install a11ywatch_cli
      - name: Start A11yWatch Service
        if: ${{ !env.EXTERNAL }}
        run: a11ywatch start
      - name: Wait for Healthy Container
        if: ${{ !env.EXTERNAL }}
        run: |
          attempt=0

          while [ $attempt -le 15 ]; do
              attempt=$(( $attempt + 1 ))
              echo "Waiting for server to be up (attempt: $attempt)..."
              result=$(docker logs api)
              if grep -q 'Server ready' <<< $result ; then
                echo "A11yWatch ready!"
                break
              fi
              sleep 0.3
          done
      - name: Scan Website
        run: |
          # run remote scan via a11ywatch.com
          if [ "$EXTERNAL" = "true" ]; then
            a11ywatch scan --url $WEBSITE_URL --external > /tmp/a11ywatch/results.json
          else
            a11ywatch scan --url $WEBSITE_URL > /tmp/a11ywatch/results.json
          fi

          # get issues count
          issues=$(jq '.website.issue | length' /tmp/a11ywatch/results.json)
          error_limit=${{ env.FAIL_ERROR_COUNT }}
          error_count=${error_limit:-0}

          if [ "$issues" -gt 0 ]; then
            echo "Issues detected $issues"

            if [ "$error_count" -gt 0 ]; then
              if [ $issues -gt "$error_count" ]; then
                  echo "Failed accessibility test!"
                  exit 1
              fi
            fi
          fi

        env:
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
          EXTERNAL: ${{ secrets.EXTERNAL }}
          FAIL_ERROR_COUNT: ${{ secrets.FAIL_ERROR_COUNT }}
      - name: Stop A11yWatch Service
        if: ${{ !env.EXTERNAL }}
        run: a11ywatch stop
