name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-container:
    name: End to End
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: A11yWatch website scan
        id: a11ywatch-results-generator
        uses: ./
        with:
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
          FAIL_TOTAL_COUNT: 100
          EXTERNAL: false
          SITE_WIDE: true
          LIST: true
          UPLOAD: true
        env:
          DEFAULT_RUNNERS: htmlcs
          PAGEMIND_IGNORE_WARNINGS: true

      - name: Get Results
        run: |
          echo "website accessibility score ${{ fromJson(steps['a11ywatch-results-generator'].outputs.results).data[0].issuesInfo.accessScore }}"
          echo ${{ toJSON(steps['a11ywatch-results-generator'].outputs.results) }} | jq ". | tojson"