name: Tests
on: [pull_request]
jobs:
  run-container:
    name: End to End
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: A11yWatch website scan
        uses: ./
        with:
          WEBSITE_URL: https://jeffmendez.com
          FAIL_TOTAL_COUNT: 100
          EXTERNAL: false
          SITE_WIDE: true
          LIST: true
          UPLOAD: true
        env:
          DEFAULT_RUNNERS: htmlcs
          PAGEMIND_IGNORE_WARNINGS: true