name: Bench Pa11y-CI
on: [pull_request]
jobs:
  build:
    name: Bench Website Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install pa11y-ci dependencies.
        run: npm install pa11y-ci  -g

      - name: Run Pa11y-CI.
        run: pa11y-ci --sitemap https://www.coinbase.com/sitemap.xml | tee pa11y_output.txt

      - name: Read pa11y_output file.
        id: pa11y_output
        uses: juliangruber/read-file-action@v1
        with:
          path: ./pa11y_output.txt

      - name: Comment on pull request.
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: '<details><summary>Pa11y testing results</summary>


```${{ steps.pa11y_output.outputs.content }}```

</details>'