name: Bench A11yWatch
on: [pull_request]
jobs:
  run-container:
    name: Bench Website Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: A11yWatch website scan
        uses: ./
        with:
          WEBSITE_URL: https://www.coinbase.com
          FAIL_TOTAL_COUNT: 10000000
          EXTERNAL: false
          SITE_WIDE: true
          SUBDOMAINS: false
          TLD: false
          LIST: true
          UPGRADE: false
          # A11YWATCH_TOKEN: ${{ secrets.A11YWATCH_TOKEN }}
